### PR TITLE
init

### PR DESCRIPTION
**Pull request by black-desk**

### CODE REVIEW

**Comment by black-desk** [comment]
fix: add some patches to fix build

Signed-off-by: black-desk <me@black-desk.cn>

------

feat: init debian directory

Signed-off-by: black-desk <me@black-desk.cn>

------

ci: add black-desk to OWNERS

Signed-off-by: black-desk <me@black-desk.cn>

------

ci: delete .github from upstream

Signed-off-by: black-desk <me@black-desk.cn>

------

chore: remove upstream debian dir

Signed-off-by: black-desk <me@black-desk.cn>

------

New upstream version 0.1.7

Signed-off-by: black-desk <me@black-desk.cn>

------

**Review by UTsweetyfish — APPROVED** [review]

**Review by hudeng-go — APPROVED** [review]

**Pull request merged**
